#
# DO NOT EDIT THIS FILE -- YOUR CHANGES WILL BE OVERWRITTEN BY DOCKER BUILD!
#

# Skip all for noninteractive shells
[ -z "$PS1" ] && return

# System wide aliases
alias ..='cd ..'
alias l='ls -alF --color=auto'
