#
# DO NOT EDIT THIS FILE -- YOUR CHANGES WILL BE OVERWRITTEN BY DOCKER BUILD!
#

# Skip all for noninteractive shells
[ -z "$PS1" ] && return

# History settings
export HISTCONTROL=""
export HISTFILESIZE=10000
export HISTIGNORE=""
export HISTSIZE=10000
export HISTTIMEFORMAT="%F %T  "
