#
# DO NOT EDIT THIS FILE -- YOUR CHANGES WILL BE OVERWRITTEN BY DOCKER BUILD!
#

# Skip all for noninteractive shells
[ -z "$PS1" ] && return

# Auto logout from console
TMOUT=3600
readonly TMOUT
export TMOUT
